name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'CMakeLists.txt'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/*.c'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'CMakeLists.txt'
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/*.c'
      
permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build directory
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make

      - name: Run tests and generate JUnit report
        run: |
          cd build
          ./tests/unit-tests/LibUnitTests --gtest_output=xml:./test-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: gtest-report
          path: build/test-report.xml

      - name: Publish Test Results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Google Test Results     # Custom name for the check
          path: build/test-report.xml   # Path to the JUnit XML report
          reporter: jest-junit          # Specify jest-junit to use the JUnit format
          fail-on-error: false
