name: CMake Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Run Tests with JUnit Report
      run: |
        mkdir build
        cd build
        cmake -DGTEST_OUTPUT=xml:gtest-report.xml ..
        make
        ./tests/unit-tests/LibUnitTests --gtest_output=xml:./gtest-report.xml

    - name: Upload Test Report
      uses: actions/upload-artifact@v3
      with:
        name: gtest-report
        path: build/gtest-report.xml

    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: GTest Results
        path: build/gtest-report.xml
        fail-on-error: false
