name: CMake Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Focando no Linux, pois você mencionou testes locais no Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build and Run Tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ./tests/unit-tests/LibUnitTests
